miry_de:
  :email: Your email
  :password: Your password
  :server_url: https://lordsandknights.com/
  :server_name: Germanien III (DE) - empfohlen
  :actions:
    - build_first
    # Send troops from each city separatly
    - send_troops_to_missions
    - research
    # Send troops cross all castles, fortress and cities
    - send_troops_from_all_cities
    # Collect prizes from completed events
    - events
    # Exchange silver from each castles with Ox carts
    - exchange_silver:
        threshold: 18000

  :buildings:

    - University area:
        level: 10

    - Residential Quarter:
        level: 10

    - Tavern Quarter:
        level: 9

    - Wood workshop:
        level: 2
    - Stone workshop:
        level: 2
    - Ore workshop:
        level: 2

    - Wood workshop:
        level: 3
    - Stone workshop:
        level: 3
    - Ore workshop:
        level: 3

    - Wood workshop:
        level: 4
    - Stone workshop:
        level: 4
    - Ore workshop:
        level: 4

    - Wood workshop:
        level: 5
    - Stone workshop:
        level: 5
    - Ore workshop:
        level: 5

    - Wood workshop:
        level: 6
    - Stone workshop:
        level: 6
    - Oreworkshop:
        level: 6

    - Wood workshop:
        level: 7
    - Stone workshop:
        level: 7
    - Ore workshop:
        level: 7

    - Wood workshop:
        level: 8
    - Stone workshop:
        level: 8
    - Ore workshop:
        level: 8

    - Wood workshop:
        level: 9
    - Stone workshop:
        level: 9
    - Ore workshop:
        level: 9

    - Wood workshop:
        level: 10
    - Stone workshop:
        level: 10
    - Ore workshop:
        level: 10

    - City Wall:
        level: 10

    - Tavern Quarter:
        level: 10

    - Military academy:
        level: 10

    - Wood storehouse:
        level: 2
    - Stone storehouse:
        level: 2
    - Ore storehouse:
        level: 2
